Search.appendIndex(
    [
                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller\\DashboardController",
            "name": "DashboardController",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Controller-DashboardController.html"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller\\DashboardController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Controller-DashboardController.html#method___construct"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller\\DashboardController\u003A\u003Adashboard_detail\u0028\u0029",
            "name": "dashboard_detail",
            "summary": "Dashboard\u0020property\u0020count\u0020view",
            "url": "../classes/Drupal-arche-dashboard-Controller-DashboardController.html#method_dashboard_detail"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller\\DashboardController\u003A\u003Adashboard_format_property_detail\u0028\u0029",
            "name": "dashboard_format_property_detail",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Controller-DashboardController.html#method_dashboard_format_property_detail"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller\\DashboardController\u003A\u003Adashboard_class_property_detail\u0028\u0029",
            "name": "dashboard_class_property_detail",
            "summary": "The\u0020rdf\u003Atype\u0020class\u0020properties\u0020detail\u0020view",
            "url": "../classes/Drupal-arche-dashboard-Controller-DashboardController.html#method_dashboard_class_property_detail"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller\\DashboardController\u003A\u003Adashboard_property_detail\u0028\u0029",
            "name": "dashboard_property_detail",
            "summary": "Dashboard\u0020property\u0020count\u0020distinct\u0020values\u0020\u0020view",
            "url": "../classes/Drupal-arche-dashboard-Controller-DashboardController.html#method_dashboard_property_detail"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller\\DashboardController\u003A\u003Adashboard_overview\u0028\u0029",
            "name": "dashboard_overview",
            "summary": "The\u0020Dashboard\u0020Main\u0020Menu\u0020View",
            "url": "../classes/Drupal-arche-dashboard-Controller-DashboardController.html#method_dashboard_overview"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller\\DashboardController\u003A\u003AgenerateView\u0028\u0029",
            "name": "generateView",
            "summary": "The\u0020basic\u0020view\u0020generation\u0020function,\u0020which\u0020will\u0020handle\u0020the\u0020sql\u0020queries\u0020based\non\u0020the\u0020passed\u0020property",
            "url": "../classes/Drupal-arche-dashboard-Controller-DashboardController.html#method_generateView"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller\\DashboardController\u003A\u003AgenerateHeaders\u0028\u0029",
            "name": "generateHeaders",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Controller-DashboardController.html#method_generateHeaders"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller\\DashboardController\u003A\u003Adashboard_property_detail_api\u0028\u0029",
            "name": "dashboard_property_detail_api",
            "summary": "The\u0020properties\u0020deatil\u0020view",
            "url": "../classes/Drupal-arche-dashboard-Controller-DashboardController.html#method_dashboard_property_detail_api"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller\\DashboardController\u003A\u003Adashboard_dissemination_services_list\u0028\u0029",
            "name": "dashboard_dissemination_services_list",
            "summary": "The\u0020properties\u0020deatil\u0020view",
            "url": "../classes/Drupal-arche-dashboard-Controller-DashboardController.html#method_dashboard_dissemination_services_list"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller\\DashboardController\u003A\u003AgetDisseminationServiceApi\u0028\u0029",
            "name": "getDisseminationServiceApi",
            "summary": "Dissemination\u0020services\u0020list\u0020api\u0020call\u0020for\u0020the\u0020datatable",
            "url": "../classes/Drupal-arche-dashboard-Controller-DashboardController.html#method_getDisseminationServiceApi"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller\\DashboardController\u003A\u003Adashboard_dissemination_services_detail\u0028\u0029",
            "name": "dashboard_dissemination_services_detail",
            "summary": "Dissemination\u0020service\u0020detail\u0020page\u0020with\u0020the\u0020basic\u0020infos",
            "url": "../classes/Drupal-arche-dashboard-Controller-DashboardController.html#method_dashboard_dissemination_services_detail"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller\\DashboardController\u003A\u003AgetDisseminationServiceMatchingResourcesApi\u0028\u0029",
            "name": "getDisseminationServiceMatchingResourcesApi",
            "summary": "The\u0020matching\u0020resource\u0020api\u0020call\u0020for\u0020the\u0020dissemination\u0020service\u0020detail\u0020datatable",
            "url": "../classes/Drupal-arche-dashboard-Controller-DashboardController.html#method_getDisseminationServiceMatchingResourcesApi"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller\\DashboardController\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Controller-DashboardController.html#property_data"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller\\DashboardController\u003A\u003A\u0024repo",
            "name": "repo",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Controller-DashboardController.html#property_repo"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller\\DashboardController\u003A\u003A\u0024model",
            "name": "model",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Controller-DashboardController.html#property_model"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller\\DashboardController\u003A\u003A\u0024helper",
            "name": "helper",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Controller-DashboardController.html#property_helper"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Helper\\DashboardHelper",
            "name": "DashboardHelper",
            "summary": "Description\u0020of\u0020DashboardHelper",
            "url": "../classes/Drupal-arche-dashboard-Helper-DashboardHelper.html"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Helper\\DashboardHelper\u003A\u003AgeneratePropertyUrl\u0028\u0029",
            "name": "generatePropertyUrl",
            "summary": "This\u0020function\u0020handle\u0020the\u0020\u0023\u0020removing\u0020problem\u0020in\u0020the\u0020browser",
            "url": "../classes/Drupal-arche-dashboard-Helper-DashboardHelper.html#method_generatePropertyUrl"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Helper\\DisseminationServiceHelper",
            "name": "DisseminationServiceHelper",
            "summary": "Description\u0020of\u0020DisseminationServiceHelper",
            "url": "../classes/Drupal-arche-dashboard-Helper-DisseminationServiceHelper.html"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Helper\\DisseminationServiceHelper\u003A\u003AgetUri\u0028\u0029",
            "name": "getUri",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Helper-DisseminationServiceHelper.html#method_getUri"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Helper\\DisseminationServiceHelper\u003A\u003AgetDissServResourcesById\u0028\u0029",
            "name": "getDissServResourcesById",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Helper-DisseminationServiceHelper.html#method_getDissServResourcesById"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Helper\\DisseminationServiceHelper\u003A\u003AgetDissServices\u0028\u0029",
            "name": "getDissServices",
            "summary": "get\u0020the\u0020available\u0020dissemination\u0020services",
            "url": "../classes/Drupal-arche-dashboard-Helper-DisseminationServiceHelper.html#method_getDissServices"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Model\\DashboardModel",
            "name": "DashboardModel",
            "summary": "Description\u0020of\u0020DashboardModel",
            "url": "../classes/Drupal-arche-dashboard-Model-DashboardModel.html"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Model\\DashboardModel\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Model-DashboardModel.html#method___construct"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Model\\DashboardModel\u003A\u003AgetViewData\u0028\u0029",
            "name": "getViewData",
            "summary": "Generate\u0020the\u0020sql\u0020data",
            "url": "../classes/Drupal-arche-dashboard-Model-DashboardModel.html#method_getViewData"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Model\\DashboardModel\u003A\u003AgetFacet\u0028\u0029",
            "name": "getFacet",
            "summary": "Retrieve\u0020the\u0020data\u003A\u0020faceting\u003A\u0020distinct\u0020values\u0020of\u0020a\u0020property",
            "url": "../classes/Drupal-arche-dashboard-Model-DashboardModel.html#method_getFacet"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Model\\DashboardModel\u003A\u003AgetFacetDetail\u0028\u0029",
            "name": "getFacetDetail",
            "summary": "Retrieve\u0020the\u0020faceting\u0020detail\u0020data",
            "url": "../classes/Drupal-arche-dashboard-Model-DashboardModel.html#method_getFacetDetail"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Model\\DashboardModel\u003A\u003AcountAllMatchingResourcesForDisseminationService\u0028\u0029",
            "name": "countAllMatchingResourcesForDisseminationService",
            "summary": "Count\u0020the\u0020selected\u0020dissemination\u0020service\u0020matching\u0020resources",
            "url": "../classes/Drupal-arche-dashboard-Model-DashboardModel.html#method_countAllMatchingResourcesForDisseminationService"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Model\\DashboardModel\u003A\u003AchangeBackDBConnection\u0028\u0029",
            "name": "changeBackDBConnection",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Model-DashboardModel.html#method_changeBackDBConnection"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Model\\DashboardModel\u003A\u003A\u0024repodb",
            "name": "repodb",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Model-DashboardModel.html#property_repodb"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Model\\DashboardModel\u003A\u003A\u0024queries",
            "name": "queries",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Model-DashboardModel.html#property_queries"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService",
            "name": "DisseminationService",
            "summary": "Description\u0020of\u0020DisseminationService",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method___construct"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetUrl\u0028\u0029",
            "name": "getUrl",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getUrl"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getId"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getTitle"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetFormats\u0028\u0029",
            "name": "getFormats",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getFormats"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetDissParams\u0028\u0029",
            "name": "getDissParams",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getDissParams"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetLocation\u0028\u0029",
            "name": "getLocation",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getLocation"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetLoadParams\u0028\u0029",
            "name": "getLoadParams",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getLoadParams"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getDescription"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetNumberOfItems\u0028\u0029",
            "name": "getNumberOfItems",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getNumberOfItems"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetReturnType\u0028\u0029",
            "name": "getReturnType",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getReturnType"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetMatchesProp\u0028\u0029",
            "name": "getMatchesProp",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getMatchesProp"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetMatchesValue\u0028\u0029",
            "name": "getMatchesValue",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getMatchesValue"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetIsPartOf\u0028\u0029",
            "name": "getIsPartOf",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getIsPartOf"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetServiceRevProxy\u0028\u0029",
            "name": "getServiceRevProxy",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getServiceRevProxy"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetCount\u0028\u0029",
            "name": "getCount",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getCount"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetFilterValues\u0028\u0029",
            "name": "getFilterValues",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getFilterValues"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AsetUrl\u0028\u0029",
            "name": "setUrl",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_setUrl"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_setTitle"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_setDescription"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AsetLocation\u0028\u0029",
            "name": "setLocation",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_setLocation"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AsetFormats\u0028\u0029",
            "name": "setFormats",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_setFormats"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AsetLoadParams\u0028\u0029",
            "name": "setLoadParams",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_setLoadParams"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AsetNumberOfItems\u0028\u0029",
            "name": "setNumberOfItems",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_setNumberOfItems"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AsetReturnType\u0028\u0029",
            "name": "setReturnType",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_setReturnType"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AsetMatchesProp\u0028\u0029",
            "name": "setMatchesProp",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_setMatchesProp"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AsetMatchesValue\u0028\u0029",
            "name": "setMatchesValue",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_setMatchesValue"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AsetIsPartOf\u0028\u0029",
            "name": "setIsPartOf",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_setIsPartOf"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AsetServiceRevProxy\u0028\u0029",
            "name": "setServiceRevProxy",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_setServiceRevProxy"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AsetCount\u0028\u0029",
            "name": "setCount",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_setCount"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AsetFilterValues\u0028\u0029",
            "name": "setFilterValues",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_setFilterValues"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_setId"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AsetDissParams\u0028\u0029",
            "name": "setDissParams",
            "summary": "Set\u0020up\u0020the\u0020dissemination\u0020service\u0020params",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_setDissParams"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetIdFromUri\u0028\u0029",
            "name": "getIdFromUri",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getIdFromUri"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetLiteral\u0028\u0029",
            "name": "getLiteral",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getLiteral"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetDisservParamLiteral\u0028\u0029",
            "name": "getDisservParamLiteral",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getDisservParamLiteral"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AsetValues\u0028\u0029",
            "name": "setValues",
            "summary": "Set\u0020the\u0020values\u0020based\u0020on\u0020the\u0020passed\u0020dissemination\u0020service\u0020object",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_setValues"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AgetMatchingResources\u0028\u0029",
            "name": "getMatchingResources",
            "summary": "Get\u0020the\u0020selected\u0020dissemination\u0020services\u0020matching\u0020results\u0020uri",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_getMatchingResources"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AcountAllMatchingResource\u0028\u0029",
            "name": "countAllMatchingResource",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_countAllMatchingResource"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003AsetDisseminationServiceFilterValues\u0028\u0029",
            "name": "setDisseminationServiceFilterValues",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#method_setDisseminationServiceFilterValues"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A\u0024obj",
            "name": "obj",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#property_obj"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A\u0024params",
            "name": "params",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#property_params"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A\u0024url",
            "name": "url",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#property_url"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#property_title"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A\u0024location",
            "name": "location",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#property_location"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A\u0024formats",
            "name": "formats",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#property_formats"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A\u0024loadParams",
            "name": "loadParams",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#property_loadParams"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#property_description"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A\u0024numberOfItems",
            "name": "numberOfItems",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#property_numberOfItems"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#property_returnType"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A\u0024matchesProp",
            "name": "matchesProp",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#property_matchesProp"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A\u0024matchesValue",
            "name": "matchesValue",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#property_matchesValue"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A\u0024isPartOf",
            "name": "isPartOf",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#property_isPartOf"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A\u0024serviceRevProxy",
            "name": "serviceRevProxy",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#property_serviceRevProxy"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A\u0024count",
            "name": "count",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#property_count"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#property_id"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A\u0024dissParams",
            "name": "dissParams",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#property_dissParams"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object\\DisseminationService\u003A\u003A\u0024filterValues",
            "name": "filterValues",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Object-DisseminationService.html#property_filterValues"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\PathProcessor\\ArcheDashboardPathProcessor",
            "name": "ArcheDashboardPathProcessor",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-PathProcessor-ArcheDashboardPathProcessor.html"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\PathProcessor\\ArcheDashboardPathProcessor\u003A\u003AprocessInbound\u0028\u0029",
            "name": "processInbound",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-PathProcessor-ArcheDashboardPathProcessor.html#method_processInbound"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits\\DisseminationServiceTrait",
            "name": "DisseminationServiceTrait",
            "summary": "Description\u0020of\u0020DisseminationServiceInterface",
            "url": "../classes/Drupal-arche-dashboard-Traits-DisseminationServiceTrait.html"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits\\DisseminationServiceTrait\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Traits-DisseminationServiceTrait.html#method___construct"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits\\DisseminationServiceTrait\u003A\u003AsetConfig\u0028\u0029",
            "name": "setConfig",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Traits-DisseminationServiceTrait.html#method_setConfig"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits\\DisseminationServiceTrait\u003A\u003AsetRepo\u0028\u0029",
            "name": "setRepo",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Traits-DisseminationServiceTrait.html#method_setRepo"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits\\DisseminationServiceTrait\u003A\u003AsetSearchTerm\u0028\u0029",
            "name": "setSearchTerm",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Traits-DisseminationServiceTrait.html#method_setSearchTerm"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits\\DisseminationServiceTrait\u003A\u003AsetRepoDb\u0028\u0029",
            "name": "setRepoDb",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Traits-DisseminationServiceTrait.html#method_setRepoDb"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits\\DisseminationServiceTrait\u003A\u003AsetSearchConfig\u0028\u0029",
            "name": "setSearchConfig",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Traits-DisseminationServiceTrait.html#method_setSearchConfig"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits\\DisseminationServiceTrait\u003A\u003AgetDisseminationServicesData\u0028\u0029",
            "name": "getDisseminationServicesData",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Traits-DisseminationServiceTrait.html#method_getDisseminationServicesData"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits\\DisseminationServiceTrait\u003A\u003AcreateDissServObj\u0028\u0029",
            "name": "createDissServObj",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Traits-DisseminationServiceTrait.html#method_createDissServObj"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits\\DisseminationServiceTrait\u003A\u003AgetDisseminationServices\u0028\u0029",
            "name": "getDisseminationServices",
            "summary": "Get\u0020the\u0020actual\u0020dissemination\u0020servcices\u0020in\u0020an\u0020array\u0020where\u0020each\narray\u0020is\u0020a\u0020dashboard\u0020dissemination\u0020service\u0020object",
            "url": "../classes/Drupal-arche-dashboard-Traits-DisseminationServiceTrait.html#method_getDisseminationServices"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits\\DisseminationServiceTrait\u003A\u003AgetDisseminationServicesById\u0028\u0029",
            "name": "getDisseminationServicesById",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Traits-DisseminationServiceTrait.html#method_getDisseminationServicesById"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits\\DisseminationServiceTrait\u003A\u003A\u0024config",
            "name": "config",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Traits-DisseminationServiceTrait.html#property_config"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits\\DisseminationServiceTrait\u003A\u003A\u0024repo",
            "name": "repo",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Traits-DisseminationServiceTrait.html#property_repo"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits\\DisseminationServiceTrait\u003A\u003A\u0024searchTerm",
            "name": "searchTerm",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Traits-DisseminationServiceTrait.html#property_searchTerm"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits\\DisseminationServiceTrait\u003A\u003A\u0024searchCfg",
            "name": "searchCfg",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Traits-DisseminationServiceTrait.html#property_searchCfg"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits\\DisseminationServiceTrait\u003A\u003A\u0024repodb",
            "name": "repodb",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Traits-DisseminationServiceTrait.html#property_repodb"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits\\DisseminationServiceTrait\u003A\u003A\u0024result",
            "name": "result",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Traits-DisseminationServiceTrait.html#property_result"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits\\DisseminationServiceTrait\u003A\u003A\u0024dissServices",
            "name": "dissServices",
            "summary": "",
            "url": "../classes/Drupal-arche-dashboard-Traits-DisseminationServiceTrait.html#property_dissServices"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "../namespaces/default.html"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "../namespaces/drupal-arche-dashboard-controller.html"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard",
            "name": "arche_dashboard",
            "summary": "",
            "url": "../namespaces/drupal-arche-dashboard.html"
        },                {
            "fqsen": "\\Drupal",
            "name": "Drupal",
            "summary": "",
            "url": "../namespaces/drupal.html"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Helper",
            "name": "Helper",
            "summary": "",
            "url": "../namespaces/drupal-arche-dashboard-helper.html"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Model",
            "name": "Model",
            "summary": "",
            "url": "../namespaces/drupal-arche-dashboard-model.html"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Object",
            "name": "Object",
            "summary": "",
            "url": "../namespaces/drupal-arche-dashboard-object.html"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\PathProcessor",
            "name": "PathProcessor",
            "summary": "",
            "url": "../namespaces/drupal-arche-dashboard-pathprocessor.html"
        },                {
            "fqsen": "\\Drupal\\arche_dashboard\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "../namespaces/drupal-arche-dashboard-traits.html"
        }            ]
);
