Search.appendIndex(
    [
                {
            "fqsen": "\\acdhOeaw\\arche\\BaseDesc",
            "name": "BaseDesc",
            "summary": "Description\u0020of\u0020BaseDesc",
            "url": "../classes/acdhOeaw-arche-BaseDesc.html"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\BaseDesc\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-BaseDesc.html#method___construct"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\ClassDesc",
            "name": "ClassDesc",
            "summary": "A\u0020container\u0020for\u0020and\u0020RDF\u0020class\u0020description",
            "url": "../classes/acdhOeaw-arche-ClassDesc.html"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\ClassDesc\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-ClassDesc.html#property_class"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\ClassDesc\u003A\u003A\u0024classes",
            "name": "classes",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-ClassDesc.html#property_classes"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\ClassDesc\u003A\u003A\u0024properties",
            "name": "properties",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-ClassDesc.html#property_properties"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\Ontology",
            "name": "Ontology",
            "summary": "Provides\u0020an\u0020API\u0020for\u0020the\u0020ARCHE\u0020oontology.",
            "url": "../classes/acdhOeaw-arche-Ontology.html"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\Ontology\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-Ontology.html#method___construct"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\Ontology\u003A\u003AisA\u0028\u0029",
            "name": "isA",
            "summary": "Checks\u0020if\u0020a\u0020given\u0020RDF\u0020resource\u0020is\u0020of\u0020a\u0020given\u0020class\u0020taking\u0020into\u0020account\nontology\u0020class\u0020inheritance.",
            "url": "../classes/acdhOeaw-arche-Ontology.html#method_isA"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\Ontology\u003A\u003AgetClass\u0028\u0029",
            "name": "getClass",
            "summary": "Returns\u0020class\u0020description.",
            "url": "../classes/acdhOeaw-arche-Ontology.html#method_getClass"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\Ontology\u003A\u003AgetProperty\u0028\u0029",
            "name": "getProperty",
            "summary": "Returns\u0020a\u0020given\u0020property\u0020description\u0020for\u0020a\u0020given\u0020RDF\u0020resource.",
            "url": "../classes/acdhOeaw-arche-Ontology.html#method_getProperty"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\Ontology\u003A\u003AloadClasses\u0028\u0029",
            "name": "loadClasses",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-Ontology.html#method_loadClasses"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\Ontology\u003A\u003AloadProperties\u0028\u0029",
            "name": "loadProperties",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-Ontology.html#method_loadProperties"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\Ontology\u003A\u003AloadRestrictions\u0028\u0029",
            "name": "loadRestrictions",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-Ontology.html#method_loadRestrictions"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\Ontology\u003A\u003Apreprocess\u0028\u0029",
            "name": "preprocess",
            "summary": "Combines\u0020class,\u0020property\u0020and\u0020restriction\u0020information",
            "url": "../classes/acdhOeaw-arche-Ontology.html#method_preprocess"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\Ontology\u003A\u003A\u0024classes",
            "name": "classes",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-Ontology.html#property_classes"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\Ontology\u003A\u003A\u0024classesRev",
            "name": "classesRev",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-Ontology.html#property_classesRev"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\Ontology\u003A\u003A\u0024properties",
            "name": "properties",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-Ontology.html#property_properties"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\Ontology\u003A\u003A\u0024restrictions",
            "name": "restrictions",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-Ontology.html#property_restrictions"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\PropertyDesc",
            "name": "PropertyDesc",
            "summary": "A\u0020container\u0020for\u0020an\u0020RDF\u0020property\u0020description",
            "url": "../classes/acdhOeaw-arche-PropertyDesc.html"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\PropertyDesc\u003A\u003A\u0024property",
            "name": "property",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-PropertyDesc.html#property_property"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\PropertyDesc\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-PropertyDesc.html#property_type"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\PropertyDesc\u003A\u003A\u0024domain",
            "name": "domain",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-PropertyDesc.html#property_domain"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\PropertyDesc\u003A\u003A\u0024properties",
            "name": "properties",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-PropertyDesc.html#property_properties"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\PropertyDesc\u003A\u003A\u0024range",
            "name": "range",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-PropertyDesc.html#property_range"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\PropertyDesc\u003A\u003A\u0024min",
            "name": "min",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-PropertyDesc.html#property_min"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\PropertyDesc\u003A\u003A\u0024max",
            "name": "max",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-PropertyDesc.html#property_max"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\RestrictionDesc",
            "name": "RestrictionDesc",
            "summary": "A\u0020container\u0020for\u0020an\u0020OWL\u0020restriction\u0020description",
            "url": "../classes/acdhOeaw-arche-RestrictionDesc.html"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\RestrictionDesc\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-RestrictionDesc.html#property_class"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\RestrictionDesc\u003A\u003A\u0024onProperty",
            "name": "onProperty",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-RestrictionDesc.html#property_onProperty"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\RestrictionDesc\u003A\u003A\u0024range",
            "name": "range",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-RestrictionDesc.html#property_range"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\RestrictionDesc\u003A\u003A\u0024min",
            "name": "min",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-RestrictionDesc.html#property_min"
        },                {
            "fqsen": "\\acdhOeaw\\arche\\RestrictionDesc\u003A\u003A\u0024max",
            "name": "max",
            "summary": "",
            "url": "../classes/acdhOeaw-arche-RestrictionDesc.html#property_max"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "../namespaces/default.html"
        },                {
            "fqsen": "\\acdhOeaw\\arche",
            "name": "arche",
            "summary": "",
            "url": "../namespaces/acdhoeaw-arche.html"
        },                {
            "fqsen": "\\acdhOeaw",
            "name": "acdhOeaw",
            "summary": "",
            "url": "../namespaces/acdhoeaw.html"
        }            ]
);
